title: Michael's Blog
description: > # this means to ignore newlines until "baseurl:"
  This is Michael Chang blog main page
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: https://twitter.com/dks50217
# Author Settings
author: Michael Chang # add your name
author-img: michael-chang.jpg # add your photo
about-author: 熱愛Trance，目前是位後端工程師，熱愛網頁開發，前端善用Vue，後端使用C#開發Web API，喜歡動手做遊戲小工具。
social-twitter: dks50217
social-facebook: dks50217
social-github: dks50217
social-linkedin: dks50217
social-email: dks50217@gmail.com

# Disqus
discus-identifier: dks50217 # add your discus identifier

# Tracker
analytics: UA-158793822-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
